### PR TITLE
fix: current session may be invalid

### LINKED ISSUE #2481: typescript sdk bug
### Rooch version

rooch 0.6.8 (git commit 82899480bd5fe65b0d7c5502ccf62f010e878b16)

### What did you do?

When I did clear session by ts sdk, sometimes comes out error. When I checking the localstorage , it seems I have 2 sessions. At that time when I clear session it will tell error : 

image

### What did you see happen?

image

### What did you expect to see?

I want it clean well. And the session should have only one.

### PR DESCRIPTION
**Pull request by newraina**
## Summary

Closes #2481 

- remove invalid session from cache storage when receive expired error
- ignore expired sessions when SDK init. (also added `isExpired` method to `Session` class)

### CODE REVIEW

**Comment by jolestar** [comment]
@wow-sven @jojoo-eth help to review

File: sdk/typescript/rooch-sdk-kit/src/provider/useRoochClient.ts
Comment (wow-sven) [inline sdk/typescript/rooch-sdk-kit/src/provider/useRoochClient.ts:1]: The hooks directory already exists useRoochClient，This code should still be on the clientProvider

File: sdk/typescript/rooch-sdk/src/session/session.ts [hunk 1]
```diff
@@ -138,6 +138,10 @@ export class Session extends Signer {
     return this.localCreateSessionTime
   }
 
+  isExpired() {
```
Comment (wow-sven) [inline sdk/typescript/rooch-sdk/src/session/session.ts:141]: isExpired fun maybe is invalid. After lastActiveTime is updated, the browser does not cache the latest value. Therefore, remove invalid sessions during sdk initialization may not work.

**Comment by wow-sven** [comment]
sdk test currently stuck. wait https://github.com/rooch-network/rooch/pull/2520
You can run tests locally

File: sdk/typescript/rooch-sdk-kit/src/provider/useRoochClient.ts
Comment (newraina) [reply sdk/typescript/rooch-sdk-kit/src/provider/useRoochClient.ts:1]: putting it in a separate file is better for testing. I can change the name to avoid conflicts.

File: sdk/typescript/rooch-sdk/src/session/session.ts (hunk 1 above)
Comment (newraina) [reply sdk/typescript/rooch-sdk/src/session/session.ts:141]: Got. After offline discussion, the `isExpired` related logic in rooch-sdk will be temporarily removed.

**Review by wow-sven — APPROVED** [review]
