### PR TITLE
[Fix Windows Build] Add Error Type In check_open_fds_limit To Fix windows build error

### LINKED ISSUE #804: [Compile Error]  Compiling on windows gives an error
```
git clone https://github.com/rooch-network/rooch.git
```

```
cd .\rooch\
```

```
cargo build
```
Get Error
```
warning: `moveos-common` (lib) generated 1 warning (run `cargo fix --lib -p moveos-common` to apply 1 suggestion)
   Compiling raw-store v0.1.0 (C:\Users\91960\Desktop\rooch\moveos\raw-store)
error[E0432]: unresolved import `moveos_common::utils::check_open_fds_limit`
  --> moveos\raw-store\src\rocks\mod.rs:15:28
   |
15 | use moveos_common::utils::{check_open_fds_limit, from_bytes};
   |                            ^^^^^^^^^^^^^^^^^^^^ no `check_open_fds_limit` in `utils`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `raw-store` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `raw-store` (lib) due to previous error
```
Environment
- Windows 11 X86
- clang version 16.0.6 Target: x86_64-pc-windows-msvc Thread model: posix

### PR DESCRIPTION
**Pull request by WGB5445**
## Summary

Summary about this PR

- Closes #804

### CODE REVIEW

File: moveos/moveos-commons/moveos-common/src/utils.rs [hunk 1]
```diff
@@ -88,6 +88,6 @@ pub fn check_open_fds_limit(max_files: u64) -> Result<(), Error> {
 }
 
 #[cfg(not(unix))]
-pub fn check_open_fds_limit(_max_files: u64) -> Result<(), ConfigError> {
+pub fn check_open_fds_limit<ConfigError>(_max_files: u64) -> Result<(), ConfigError> {
```
Comment (baichuan3) [inline moveos/moveos-commons/moveos-common/src/utils.rs:91]: try function ?
```
#[cfg(not(unix))]
pub fn check_open_fds_limit(_max_files: u64) -> Result<(), Error>
```

Comment (WGB5445) [reply moveos/moveos-commons/moveos-common/src/utils.rs:91]: > try function ?
> 
> ```
> #[cfg(not(unix))]
> pub fn check_open_fds_limit(_max_files: u64) -> Result<(), Error>
> ```

Thank you very much, good suggestion, it is better to use Error for errors here

**Review by baichuan3 — APPROVED** [review]
