### PR TITLE
[genesis] Fix Sequencer config for genesis

### LINKED ISSUE #1668: [Genesis] Use a fixed sequencer address for testnet and mainnet

### PR DESCRIPTION
**Pull request by jolestar**
## Summary

1. [cli] remove bitcoin network option
2. Add genesis_block_height to GenesisConfig and remove btc_start_block_height from cli.
3. Stop change gas for bypass_visibility function(L1 block tx), and give init gas to sequencer.

- Closes #1668

### CODE REVIEW

File: crates/rooch-types/src/bitcoin/genesis.rs [hunk 1]
```diff
@@ -24,12 +25,16 @@ impl MoveStructState for BitcoinGenesisContext {
...
         ])
     }
 }
 
 impl BitcoinGenesisContext {
-    pub fn new(network: u8) -> Self {
-        Self { network }
+    pub fn new(network: u8, genesis_block_height: u64) -> Self {
+        Self {
+            network,
```
Comment (baichuan3) [inline crates/rooch-types/src/bitcoin/genesis.rs:36]: After removing the cli and passing in bitcoin_network, is there a one-to-one correspondence between bitcoin_network and RoochChainID?

Comment (jolestar) [reply crates/rooch-types/src/bitcoin/genesis.rs:36]: Yes. We can use a custom chain to bind any bitcoin network to any rooch chain config.

**Review by baichuan3 — APPROVED** [review]
