### PR TITLE
fix: Display vector byte if movestring can't format to utf8

### LINKED ISSUE #2388: System Panic
thread 'tokio-runtime-worker' panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/string.rs:2554:14:
a Display implementation returned an error unexpectedly: Error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```txt
thread 'tokio-runtime-worker' panicked at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/string.rs:2554:14:
a Display implementation returned an error unexpectedly: Error
stack backtrace:
   0:     0x5992aec46972 - std::backtrace_rs::backtrace::libunwind::trace::he4ee80166a02c846
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x5992aec46972 - std::backtrace_rs::backtrace::trace_unsynchronized::h476faccf57e88641
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5992aec46972 - std::sys_common::backtrace::_print_fmt::h430c922a77e7a59c
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5992aec46972 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5992aec7ab2c - core::fmt::rt::Argument::fmt::hf3df69369399bfa9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/rt.rs:142:9
   5:     0x5992aec7ab2c - core::fmt::write::hd9a8d7d029f9ea1a
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/mod.rs:1153:17
   6:     0x5992aec40ebf - std::io::Write::write_fmt::h0e1226b2b8d973fe
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/io/mod.rs:1843:15
   7:     0x5992aec46744 - std::sys_common::backtrace::_print::hd2df4a083f6e69b8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5992aec46744 - std::sys_common::backtrace::print::he907f6ad7eee41cb
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5992aec480eb - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
  10:     0x5992aec47e43 - std::panicking::default_hook::h25ba2457dea68e65
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:292:9
  11:     0x5992a7bc6ec4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc5a74d66c5b94b3d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  12:     0x5992a745f4c4 - rooch_rpc_server::run_start_server::{{closure}}::{{closure}}::hce1cd83f688b221c
                               at /rooch/crates/rooch-rpc-server/src/lib.rs:175:9
  13:     0x5992aec48790 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h022ca2c0d8c21c9e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  14:     0x5992aec48790 - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
  15:     0x5992aec484d2 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
  16:     0x5992aec46e46 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
  17:     0x5992aec48204 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
  18:     0x5992aec77bc5 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
  19:     0x5992aec78213 - core::result::unwrap_failed::h5119205a73b72b0d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
  20:     0x5992adc9be58 - core::result::Result<T,E>::expect::h9ac443606d351b09
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1034:23
  21:     0x5992ad4162e7 - <T as alloc::string::ToString>::to_string::heffbeb55c7d34df6
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/string.rs:2553:9
  22:     0x5992a7f430f7 - <moveos_types::move_std::string::MoveString as serde::ser::Serialize>::serialize::he903ee924a076377
                               at /rooch/moveos/moveos-types/src/move_std/string.rs:103:38
  23:     0x5992a7f2112c - rooch_rpc_api::jsonrpc_types::move_types::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::move_types::SpecificStructView>::serialize::h2565dbcee11bba8f
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs:154:24
  24:     0x5992a7f213bb - rooch_rpc_api::jsonrpc_types::move_types::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::move_types::AnnotatedMoveValueView>::serialize::h3b7b74b64e72ce35
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs:182:24
  25:     0x5992a7f23419 - serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize::h8dc864a38e38d5d7
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:521:17
  26:     0x5992a7f9676f - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::h10e7692b6da9ec48
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  27:     0x5992a7f958fd - serde::ser::SerializeMap::serialize_entry::hf200b5d4b2beab55
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  28:     0x5992a7f3b9c0 - serde::ser::Serializer::collect_map::{{closure}}::h0d2ee3729a34e61c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1326:47
  29:     0x5992a7d9a06a - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::h2e3ad243a606cc58
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2468:26
  30:     0x5992a7d97545 - core::iter::traits::iterator::Iterator::try_fold::h6e6fc86c132f0b62
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2409:21
  31:     0x5992a7d9730e - core::iter::traits::iterator::Iterator::try_for_each::hb5f718a312f042c7
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2471:9
  32:     0x5992a7f8dcc9 - serde::ser::Serializer::collect_map::hbe2791d281491dd8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1326:14
  33:     0x5992a7d97b91 - serde::ser::impls::<impl serde::ser::Serialize for alloc::collections::btree::map::BTreeMap<K,V>>::serialize::h2fdd6ca798f41c8d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:465:17
  34:     0x5992a7f9ca4f - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::hfe22919da0ca8b6f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  35:     0x5992a7f93ba1 - serde::ser::SerializeMap::serialize_entry::h4cb9e90059894b90
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  36:     0x5992a7fa10d3 - <serde_json::ser::Compound<W,F> as serde::ser::SerializeStruct>::serialize_field::h9071fee4370066d2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:693:37
  37:     0x5992a7f21939 - rooch_rpc_api::jsonrpc_types::move_types::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::move_types::AnnotatedMoveStructView>::serialize::h772ddc060754a7ff
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs:130:24
  38:     0x5992a7f21396 - rooch_rpc_api::jsonrpc_types::move_types::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::move_types::AnnotatedMoveValueView>::serialize::h3b7b74b64e72ce35
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs:182:24
  39:     0x5992a7f23419 - serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize::h8dc864a38e38d5d7
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:521:17
  40:     0x5992a7f9676f - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::h10e7692b6da9ec48
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  41:     0x5992a7f958fd - serde::ser::SerializeMap::serialize_entry::hf200b5d4b2beab55
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  42:     0x5992a7f3b9c0 - serde::ser::Serializer::collect_map::{{closure}}::h0d2ee3729a34e61c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1326:47
  43:     0x5992a7d9a06a - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::h2e3ad243a606cc58
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2468:26
  44:     0x5992a7d97545 - core::iter::traits::iterator::Iterator::try_fold::h6e6fc86c132f0b62
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2409:21
  45:     0x5992a7d9730e - core::iter::traits::iterator::Iterator::try_for_each::hb5f718a312f042c7
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2471:9
  46:     0x5992a7f8dcc9 - serde::ser::Serializer::collect_map::hbe2791d281491dd8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1326:14
  47:     0x5992a7d97b91 - serde::ser::impls::<impl serde::ser::Serialize for alloc::collections::btree::map::BTreeMap<K,V>>::serialize::h2fdd6ca798f41c8d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:465:17
  48:     0x5992a7f9ca4f - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::hfe22919da0ca8b6f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  49:     0x5992a7f93ba1 - serde::ser::SerializeMap::serialize_entry::h4cb9e90059894b90
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  50:     0x5992a7fa10d3 - <serde_json::ser::Compound<W,F> as serde::ser::SerializeStruct>::serialize_field::h9071fee4370066d2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:693:37
  51:     0x5992a7f21939 - rooch_rpc_api::jsonrpc_types::move_types::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::move_types::AnnotatedMoveStructView>::serialize::h772ddc060754a7ff
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/move_types.rs:130:24
  52:     0x5992a7fa4421 - <&mut serde_json::ser::Serializer<W,F> as serde::ser::Serializer>::serialize_some::hf96829b42c87cedf
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:276:9
  53:     0x5992a7d93378 - serde::ser::impls::<impl serde::ser::Serialize for core::option::Option<T>>::serialize::h17d11a3da129aa52
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:109:32
  54:     0x5992a7f9c2df - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::heee941941af03c2b
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  55:     0x5992a7f95121 - serde::ser::SerializeMap::serialize_entry::hc0e514c4731fcd6c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  56:     0x5992a7e895f3 - rooch_rpc_api::jsonrpc_types::state_view::_::<impl serde::ser::Serialize for rooch_rpc_api::jsonrpc_types::state_view::ObjectStateView>::serialize::h661237eb480a8ed4
                               at /rooch/crates/rooch-rpc-api/src/jsonrpc_types/state_view.rs:411:24
  57:     0x5992a7fa40f1 - <&mut serde_json::ser::Serializer<W,F> as serde::ser::Serializer>::serialize_some::h0855573cd4a410f4
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:276:9
  58:     0x5992a7d9344f - serde::ser::impls::<impl serde::ser::Serialize for core::option::Option<T>>::serialize::h1fab8dfd727f6d35
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:109:32
  59:     0x5992a7d93219 - serde::ser::impls::<impl serde::ser::Serialize for &T>::serialize::h067c1badd4a35cf8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:521:17
  60:     0x5992a7f9dc6d - <serde_json::ser::Compound<W,F> as serde::ser::SerializeSeq>::serialize_element::h61f3e21daa6f7802
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:498:22
  61:     0x5992a7f3bda0 - serde::ser::Serializer::collect_seq::{{closure}}::h5c40490644b9b2c1
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1288:39
  62:     0x5992a7d9a53e - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::hda2d2381a36a133d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2468:26
  63:     0x5992a7eea32d - core::iter::traits::iterator::Iterator::try_fold::h36cde1180a2c5f85
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2409:21
  64:     0x5992a7ee95ee - core::iter::traits::iterator::Iterator::try_for_each::ha92d1817a70ef945
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/iter/traits/iterator.rs:2471:9
  65:     0x5992a7f8f9fd - serde::ser::Serializer::collect_seq::h690f4819e70d4dd3
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1288:14
  66:     0x5992a7f54261 - serde::ser::impls::<impl serde::ser::Serialize for alloc::vec::Vec<T>>::serialize::h6dfb1526eef4c4f8
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:204:17
  67:     0x5992a7fa60a6 - serde::ser::impls::<impl serde::ser::Serialize for alloc::borrow::Cow<T>>::serialize::he08ee885d0c00897
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/impls.rs:521:17
  68:     0x5992a7f9985f - <serde_json::ser::Compound<W,F> as serde::ser::SerializeMap>::serialize_value::h88095eef3c581e86
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:652:22
  69:     0x5992a7f94231 - serde::ser::SerializeMap::serialize_entry::h618492bc506db8d4
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.204/src/ser/mod.rs:1817:9
  70:     0x5992a7f9f493 - <serde_json::ser::Compound<W,F> as serde::ser::SerializeStruct>::serialize_field::h095eec846c6e8c42
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:693:37
  71:     0x5992a7fd8ceb - <jsonrpsee_types::response::Response<T> as serde::ser::Serialize>::serialize::hdc199eb6dca0b953
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-types-0.23.2/src/response.rs:332:35
  72:     0x5992a7f8d522 - serde_json::ser::to_writer::hda0c3e60e810b879
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/serde_json-1.0.122/src/ser.rs:2145:5
  73:     0x5992a7e7fae8 - jsonrpsee_core::server::method_response::MethodResponse::response::hf203aaef8a908e93
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-core-0.23.2/src/server/method_response.rs:160:9
  74:     0x5992a7f30344 - jsonrpsee_core::server::rpc_module::RpcModule<Context>::register_async_method::{{closure}}::{{closure}}::hacba3ed1f950ae28
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-core-0.23.2/src/server/rpc_module.rs:596:6
  75:     0x5992a762264a - <core::pin::Pin<P> as core::future::future::Future>::poll::h7b60166aceb6b2f2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  76:     0x5992a7884be2 - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h78cfd8709192f94d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/either.rs:109:32
  77:     0x5992a7b9a50e - <jsonrpsee_server::middleware::rpc::layer::ResponseFuture<F> as core::future::future::Future>::poll::h677b0671047c5631
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-server-0.23.2/src/middleware/rpc/layer/mod.rs:64:3
  78:     0x5992a74696b8 - jsonrpsee_server::server::handle_rpc_call::{{closure}}::hb35eb069bea526d6
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-server-0.23.2/src/server.rs:1283:31
  79:     0x5992a7461c89 - jsonrpsee_server::transport::http::call_with_service::{{closure}}::h0b50dce81335ad20
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-server-0.23.2/src/transport/http.rs:99:6
  80:     0x5992a76622f2 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hc0203d7fe263de81
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  81:     0x5992a765fe3e - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hbdd8e8ba0aa2ad77
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  82:     0x5992a7622a5a - <core::pin::Pin<P> as core::future::future::Future>::poll::h93b1777435e5566f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  83:     0x5992a77672c0 - <tower_http::cors::ResponseFuture<F> as core::future::future::Future>::poll::h88e3493bb3829978
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.5.2/src/cors/mod.rs:686:56
  84:     0x5992a7c9fce0 - <tower_http::trace::future::ResponseFuture<Fut,C,OnResponseT,OnBodyChunkT,OnEosT,OnFailureT> as core::future::future::Future>::poll::h894d5aa180d5ced9
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.5.2/src/trace/future.rs:55:29
  85:     0x5992a7682cb5 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h7516f44048d32530
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.4.13/src/util/oneshot.rs:97:38
  86:     0x5992a777f21e - <jsonrpsee_server::utils::TowerToHyperServiceFuture<S,R> as core::future::future::Future>::poll::h03f99d2829a10180
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-server-0.23.2/src/utils.rs:82:3
  87:     0x5992a7623ebb - <hyper::proto::h1::dispatch::Server<S,hyper::body::incoming::Incoming> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::hf913b5a05edb217c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:514:35
  88:     0x5992a7625bc9 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::hbb81798be51e0d43
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:312:43
  89:     0x5992a7627e81 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop::hc2f3bf47ddd91261
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:171:21
  90:     0x5992a762566e - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::h9318b40a8fb0b364
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:147:16
  91:     0x5992a76252e9 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::hd003522a4b5f9f0e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:126:28
  92:     0x5992a7623d1c - <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll::h5f974236acf010f5
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/proto/h1/dispatch.rs:447:9
  93:     0x5992a78841e0 - <hyper::server::conn::http1::UpgradeableConnection<I,S> as core::future::future::Future>::poll::hae9172320804967f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-1.3.1/src/server/conn/http1.rs:505:26
  94:     0x5992a781fa32 - <hyper_util::server::conn::auto::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hee34756a49f8dd09
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.3/src/server/conn/auto.rs:475:28
  95:     0x5992a7621b7b - <core::pin::Pin<P> as core::future::future::Future>::poll::h24450572ee827812
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  96:     0x5992a76201a9 - futures_util::future::future::FutureExt::poll_unpin::he49b2ada7a056b18
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
  97:     0x5992a7b9c0aa - <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll::h84122a6dfb76efb6
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:114:35
  98:     0x5992a746d41a - jsonrpsee_server::server::process_connection::{{closure}}::h9d3ff29e87378fdd
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-server-0.23.2/src/server.rs:1230:49
  99:     0x5992a7623344 - <core::pin::Pin<P> as core::future::future::Future>::poll::he996bed17e8b76f2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
 100:     0x5992a79d83c7 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hba1993d8d7e90094
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
 101:     0x5992a79c21c6 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h8ab1184f306551d2
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
 102:     0x5992a79c21c6 - tokio::runtime::task::core::Core<T,S>::poll::h2d3af23d53dde589
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
 103:     0x5992a790b55f - tokio::runtime::task::harness::poll_future::{{closure}}::h4e4bd42d05855877
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
 104:     0x5992a7ba7d99 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h17f90390a2c5a5d2
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
 105:     0x5992a77fcf3d - std::panicking::try::do_call::h86cf05948f148a62
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
 106:     0x5992a781f5cd - __rust_try
 107:     0x5992a77db6ae - std::panicking::try::h45b2a09489e787db
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
 108:     0x5992a7973055 - std::panic::catch_unwind::h271cb1c2c0a9348f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
 109:     0x5992a78f6041 - tokio::runtime::task::harness::poll_future::h4a69cbf52c993b53
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
 110:     0x5992a791f693 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::ha8fabaf44c6af353
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
 111:     0x5992a7940629 - tokio::runtime::task::harness::Harness<T,S>::poll::h4270523084106fcc
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
 112:     0x5992a78cf91f - tokio::runtime::task::raw::poll::ha7774e1d9e242d73
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
 113:     0x5992ae4e6947 - tokio::runtime::task::raw::RawTask::poll::h3a10cb4cae6a83f5
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
 114:     0x5992ae4a80a4 - tokio::runtime::task::LocalNotified<S>::run::h49d1e32385dacb16
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:427:9
 115:     0x5992ae4bc370 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h0e79c9a60f72b186
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:657:17
 116:     0x5992ae4bbca5 - tokio::runtime::coop::with_budget::h2bba97ceb21c6573
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
 117:     0x5992ae4bbca5 - tokio::runtime::coop::budget::h1cdf0d7c31e8754a
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
 118:     0x5992ae4bbca5 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h90e8072c70c3ea16
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:593:9
 119:     0x5992ae4bb475 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h845378045e02785e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:544:24
 120:     0x5992ae4bb140 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::hb43abb2954b486e9
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:509:21
 121:     0x5992ae4a72a0 - tokio::runtime::context::scoped::Scoped<T>::set::h56047115e8531cd4
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/scoped.rs:40:9
 122:     0x5992ae46a75c - tokio::runtime::context::set_scheduler::{{closure}}::hd512ed24c391b77c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:26
 123:     0x5992ae49f5e9 - std::thread::local::LocalKey<T>::try_with::h0c8b1e34b9fd1394
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:284:16
 124:     0x5992ae49f2a2 - std::thread::local::LocalKey<T>::with::h92fac3490ddbdeb9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:260:9
 125:     0x5992ae46a641 - tokio::runtime::context::set_scheduler::h513aff4ec29623f3
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context.rs:180:9
 126:     0x5992ae4bb05a - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h00e3ac25446c0dc6
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:504:9
 127:     0x5992ae500148 - tokio::runtime::context::runtime::enter_runtime::hf565556c2dd43c5f
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
 128:     0x5992ae4bae52 - tokio::runtime::scheduler::multi_thread::worker::run::haff02919b3e40868
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:496:5
 129:     0x5992ae4baba2 - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}::hcbfdb7c8c08db350
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/worker.rs:462:45
 130:     0x5992ae4c4f66 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::he1782797825695f7
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/task.rs:42:21
 131:     0x5992ae4ccaf6 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h403a246d25756eca
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:328:17
 132:     0x5992ae4cbbf6 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::ha71d39a70768f153
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/loom/std/unsafe_cell.rs:16:9
 133:     0x5992ae4cbbf6 - tokio::runtime::task::core::Core<T,S>::poll::h6b0a617e36d1e538
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/core.rs:317:13
 134:     0x5992ae49dabf - tokio::runtime::task::harness::poll_future::{{closure}}::hf603b38915e32d5b
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:485:19
 135:     0x5992ae4d28f9 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h518b926bcea007b6
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
 136:     0x5992ae48f75d - std::panicking::try::do_call::h172ffd65892816a8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
 137:     0x5992ae493e6d - __rust_try
 138:     0x5992ae48f38e - std::panicking::try::hf1ce5b1b2234e04d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
 139:     0x5992ae46d625 - std::panic::catch_unwind::hb6a5850bea0c4363
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
 140:     0x5992ae49cdb1 - tokio::runtime::task::harness::poll_future::he6377f468816f39e
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:473:18
 141:     0x5992ae4967a3 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h884e1b92bf956732
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:208:27
 142:     0x5992ae495799 - tokio::runtime::task::harness::Harness<T,S>::poll::h355e687ad45a915c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/harness.rs:153:15
 143:     0x5992ae4e6bbf - tokio::runtime::task::raw::poll::h13b2661d71a97d13
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:271:5
 144:     0x5992ae4e6947 - tokio::runtime::task::raw::RawTask::poll::h3a10cb4cae6a83f5
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/raw.rs:201:18
 145:     0x5992ae4a8196 - tokio::runtime::task::UnownedTask<S>::run::h925a78d92645f62c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/task/mod.rs:464:9
 146:     0x5992ae4bed19 - tokio::runtime::blocking::pool::Task::run::h2f5aac1f68eaf848
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:160:9
 147:     0x5992ae4c3946 - tokio::runtime::blocking::pool::Inner::run::h955a3449934f877d
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:518:17
 148:     0x5992ae4c36ca - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hd35474e3f0919d8c
                               at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/blocking/pool.rs:476:13
 149:     0x5992ae4fb71d - std::sys_common::backtrace::__rust_begin_short_backtrace::h093e78ef62fbc4b3
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
 150:     0x5992ae4a2811 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h7befcb132e7af602
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:528:17
 151:     0x5992ae4d2c51 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h977b469ba3f0229f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panic/unwind_safe.rs:272:9
 152:     0x5992ae48fee1 - std::panicking::try::do_call::h6c48627061d8443a
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
 153:     0x5992ae493e6d - __rust_try
 154:     0x5992ae48df59 - std::panicking::try::h64e7516317559e2b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
 155:     0x5992ae4a2635 - std::panic::catch_unwind::h902437789ef1384f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
 156:     0x5992ae4a2635 - std::thread::Builder::spawn_unchecked_::{{closure}}::he37a9f80dc732595
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:527:30
 157:     0x5992ae514da2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h839c3bace1c311fa
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
 158:     0x5992aec4e8a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h19b9e642d37e7272
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
 159:     0x5992aec4e8a5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h97265befc434d3ae
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
 160:     0x5992aec4e8a5 - std::sys::pal::unix::thread::Thread::new::thread_start::h420dad5cf01a9f35
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/unix/thread.rs:108:17
 161:     0x74cde8ccaac3 - <unknown>
 162:     0x74cde8d5ba04 - __clone
 163:                0x0 - <unknown>
```

### PR DESCRIPTION
**Pull request by qShirley**
## Summary

Summary about this PR

- Closes #2388

### CODE REVIEW

File: moveos/moveos-types/src/move_std/string.rs [hunk 1]
```diff
@@ -35,11 +35,14 @@ impl std::fmt::Debug for MoveString {
...
-        write!(
-            f,
-            "{}",
-            std::str::from_utf8(&self.bytes).map_err(|_| std::fmt::Error)?
-        )
+        match std::str::from_utf8(&self.bytes) {
+            Ok(s) => {
+                write!(f, "{}", s)
+            }
+            Err(_) => {
```
Comment (baichuan3) [inline moveos/moveos-types/src/move_std/string.rs:42]: MoveString is new with utf8 check in the contract, and the Rust implementation should also check utf8

**Review by baichuan3 — APPROVED** [review]

File: moveos/moveos-types/src/move_std/string.rs (hunk 1 above)
Comment (jolestar) [reply moveos/moveos-types/src/move_std/string.rs:42]: If MoveString is a transaction argument or directly deserialized via bcs::from_bcs, we can not check the utf8.

**Comment by jolestar** [comment]
I merge this PR first, but we need to add a test case.

**Comment by qShirley** [comment]
I have a simple test in local, but more test is better
