### PR TITLE
[framework] Fix session key create session key bug

### LINKED ISSUE #1625: [bug] SessionKey can create SessionKey
https://github.com/rooch-network/rooch/blob/417f226614f56caa4e8657a067d9bf952567530f/frameworks/rooch-framework/sources/session_key.move#L116-L117

The assert ensures users can not use a SessionKey to create a new SessionKey, but it does not work. 

## Reason

https://github.com/rooch-network/rooch/blob/417f226614f56caa4e8657a067d9bf952567530f/crates/rooch-types/src/framework/auth_validator.rs#L152-L164

the `transaction_validtor` of above should `transaction_validator`.

1. All the logic with `TxValidateResult` should be checked.
2. Write a test to ensure the assert.

### PR DESCRIPTION
**Pull request by jolestar**
## Summary

Fix session key create session key bug

- Closes #1625

### CODE REVIEW

File: crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs [hunk 1]
```diff
@@ -113,17 +108,55 @@ fn test_session_key_rooch() {
...
+        KeptVMStatus::MoveAbort(l, code) => {
+            match l {
+                AbortLocation::Module(module_id) => {
+                    assert_eq!(
+                        module_id,
+                        SessionKeyModule::module_id(),
+                        "expect session key module"
+                    );
+                }
+                _ => panic!("expect move abort in module"),
```
Comment (baichuan3) [inline crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs:139]: Directly panic? Or throw an Error?

Comment (jolestar) [reply crates/rooch-framework-tests/src/tests/transaction_validator_tests.rs:139]: The test case no Result

**Review by baichuan3 — APPROVED** [review]
