### PR TITLE
[MoveOS] Fix raw_table error code bug

### LINKED ISSUE #635: Move explain error code mismatch
**error message**
```
  "execution_info": {
    "tx_hash": "0x2f4bcaeb4811c2a55e1ebf4b28b4659dc8752f23639bc6e5bb317bec532bd487",
    "state_root": "0xc59c16d5689786bd36c23c54f2f341a7e317f5d81b07ddc99f8ebbfb5c3571bf",
    "event_root": "0x414343554d554c41544f525f504c414345484f4c4445525f4841534800000000",
    "gas_used": 0,
    "status": {
      "type": "moveabort",
      "location": "0000000000000000000000000000000000000000000000000000000000000002::raw_table",
      "abort_code": "25863"
    }
  },
```

**explain error code**
```
rooch move explain --location 0000000000000000000000000000000000000000000000000000000000000002::raw_table --abort-code 25863

Category Code: 0
Category Name: Unknown
Reason Code: 25863
Reason Name: Unknown
Code Description: Unknown

Success
```

**reason:**
Now << 16 in error and <<8 in rust

### PR DESCRIPTION
**Pull request by jolestar**
## Summary

Refactor the raw_table error code bug

```bash
rooch move explain -a 524289 -l 0x2::raw_table
Category Code: 8
Category Name: ALREADY_EXISTS
Reason Code: 1
Reason Name: EAlreadyExists
Code Description:  The key already exists in the table
```

- Closes #635

### CODE REVIEW

File: moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs [hunk 1]
```diff
@@ -44,17 +44,15 @@ pub struct NativeTableContext<'a> {
...
-//25607
-const ALREADY_EXISTS: u64 = (100 << 8) + ECATEGORY_INVALID_ARGUMENT as u64;
-//25863
-const NOT_FOUND: u64 = (101 << 8) + ECATEGORY_INVALID_ARGUMENT as u64;
-// Move side raises this
-//26112
-const NOT_EMPTY: u64 = (102 << 8) + _ECATEGORY_INVALID_STATE as u64;
+//524289
+const ALREADY_EXISTS: u64 =
+    moveos_types::move_std::error::canonical(moveos_types::move_std::error::ALREADY_EXISTS, 1);
```
Comment (baichuan3) [inline moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs:49]: Is there a one-to-one correspondence between the number in the second parameter of canonical in Rust and the error code definition EAlreadyExists, ENotFound, ENotEmpty in `raw_table.move`? It will be easier to understand and maintain if the definition can be unified in Rust and Move.

Comment (jolestar) [reply moveos/moveos-stdlib/src/natives/moveos_stdlib/raw_table/mod.rs]: Refactor, I keep the error codes in `raw_table/mode.rs` the same as the error codes in `raw_table.move`

**Review by baichuan3 — APPROVED** [review]
